### ISSUE TITLE
Is there a download link for the schematic?

### ISSUE THREAD

**Issue by EdXian** [s887432/sam9x60_hobby-patch#1]
Hi ,
I got a new sam9x60 hobby board recently. I want to wire the pin for my project. However, I can't find the schematic or other sources from [here].(https://www.microchip.com.tw/index.php).
Could you please provide the schematic for sam9x60 hobby board? 
Best Regards!

**Comment by s887432** [comment]
Hi PinXain,

Thank you very much for your mail.
For your inquiry, I'll ask CAE to publish the schematic.

Thank you very much.

Patrick

**Comment by s887432** [comment]
Hi Pinxian,

The schematic is uploaded.
Please check following doc for detail information or visit Microchip Taiwan
web site.

Thanks.

Patrick

**Comment by EdXian** [comment]
Hi Patrick,
Thank you very much!
For those who wants to download the schematic, please refer to the [guide](https://www.microchip.com.tw/uploads/tad_uploader/tmp/131/APP_SAM9X60_Dev_Resource.pdf).
