### ISSUE TITLE
Is it possible connect a parallel camera (8bit~12bit) with sam9x60_hobby?

### ISSUE THREAD

**Issue by EdXian** [s887432/sam9x60_hobby-patch#2]
Hi @s887432,
I want to integrate a camera module with the hobby board. However, the LCD interface 
 dosen't include the PC0(ISI-D0), PC1(ISI-D1) PC8(ISI-D8) PC9(ISI-D9). Is it possible to map the ISI pin to other GPIOs and drive a camera module?
Thank you very much!

**Comment by s887432** [comment]
Hi PinXian,

First at all.
The ISI interface are shared pin with LCD.
you can't use LCD and ISI at the same time.

The display interface design was RGB666 only.
Some pins are not connected to LCD connector, sucn as PC0 (ISI_D0) and
PC1(ISI_D1).
Fortunately, those two pins are assigned to mikroBUS TX/RX.
Still able to use it.
Of cause, you have to modify device tree to fit this assignment.
Same as PC8 (ISI_D8) and PC9 (ISI_D9),
They are assigned to RPi connectors.

Please check schematic for more details.
thanks.

https://www.microchip.com.tw/uploads/tad_uploader/tmp/128/SAM9X60-HobbyKit-20220908.pdf

Best regards

Patrick
