### ISSUE TITLE
Is there a tutorial  for sam9x60 hobby board?

### ISSUE THREAD

**Issue by EdXian** [s887432/sam9x60_hobby-patch#3]
Hi @s887432 ,
I want to bring up uart, i2c and spi (mikrobus) for my project. Then I go to the website Linux4sam to find the detail tutorial about the device tree and driver. However i cannot find it. Is there a material for sam9x60 hobby board?  
Best regards, 
Ed

**Comment by s887432** [comment]
Hi Pnxian,

you can refer to SAMA5D2 application node.
it's almost same. only pin assignment different.
https://www.microchip.com/en-us/product/ATSAMA5D27#document-table

please feel free to let me know if any trouble you found.

BTW, are you planning to use sam9x60 for your project?

Thanks..

best regards,

Patrick

**Comment by EdXian** [comment]
hi @s887432 ,
Thnak you for your suggestion.
Yes, i am going to do my side project which is an ip camera.
Best regards,
Ed
